---
title: "Modeling player salary"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{salary}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mlbgm)
```


```{r}
these_comps <- comps("beltrca01", 2005)
earnings <- these_comps$comps_universe %>%
  filter(salary > 0, !is.na(age))
```

## Visualization

```{r}
ggplot(earnings, 
       aes(x = mlb_exp, y = salary, color = rWAR)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  scale_y_log10("Actual Salary (USD)", labels = scales::dollar) + 
  scale_color_viridis_c()
```

## Modeling

```{r}
mods <- list(
  "simple" = lm(salary ~ factor(mlb_exp) + rWAR + age + factor(yearId), data = earnings), 
  
  "log" = lm(log(salary) ~ factor(mlb_exp) + rWAR + age + factor(yearId), data = earnings), 
  "log_quadratic" = lm(log(salary) ~ factor(mlb_exp) + rWAR + poly(age, 2) + factor(yearId), data = earnings)
)

mods %>%
  map_dfr(glance, .id = "model")

mod_earnings <- mods[["log_quadratic"]]
```

```{r}
earnings_aug <- mod_earnings %>%
  augment(data = earnings) %>%
  mutate(.resid = salary - exp(.fitted))

earnings_aug %>%
  group_by(playerId) %>%
  summarize(overpaid = sum(.resid)) %>%
  arrange(desc(overpaid))
```
